# Conda environment file for developers
name: softworks-dev
channels:
  - conda-forge
  - defaults
dependencies:
# Development
  - pytest=7.1.2
  - pylint=2.14.4
  - mypy == 0.961
  - pre-commit=2.20.0
# Documentation
  - sphinx = 4.5.0
  - pydata-sphinx-theme = 0.9.0
  - sphinx-panels = 0.6.0
  - sphinx-copybutton = 0.5.0
  - sphinx-autobuild = 2021.3.14
  - sphinx-github-changelog = 1.2.0
  - esbonio = 0.13.1
